run:
  timeout: 5m
  tests: true

issues:
  exclude-use-default: false
  exclude-files:
    - '\.gen\.go'
    - '\.pb\.go'
  exclude-dirs:
    - vendor
    - .git
    - node_modules
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - govet
        - staticcheck
        - gosimple
        - unused
        - ineffassign
        - typecheck
        - gofmt
        - goimports
        - misspell
        - unconvert
        - gocyclo
        - dupl
        - goconst
        - gosec
        - depguard
        - gocritic
        - lll
        - nakedret
        - prealloc
        - stylecheck
        - unparam
        - whitespace

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocyclo
    - dupl
    - goconst
    - gosec
    - depguard
    - gocritic
    - lll
    - nakedret
    - prealloc
    - stylecheck
    - unparam
    - whitespace
    - gci

linters-settings:
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 120
  misspell:
    locale: US
  dupl:
    threshold: 100
  gosec:
    excludes:
      - G104

  gocritic:
    enabled-checks:
      - ruleguard

output:
  formats:
    - format: colored-line-number