name: Embassy-monitoring pipeline
on:
  push:
    branches:
      - "*"
    tags:
      - 'v*.*.*'
  workflow_dispatch:
permissions:
  contents: write
env:
  GOLANGCI_LINT_VERSION: v1.64.5

jobs:
  lint-golangci:
    runs-on: ubuntu-22.04
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Linters
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: ${{ env.BRANCH }}


  build:
    runs-on: ubuntu-22.04
    if: github.event_name == 'push'
    needs: lint-golangci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Run tests
        run: go test ./... -tags=unit
      - name: Build
        run: go build -o embassy-monitoring
      - name: List files
        run: ls -la
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'error'
          name: embassy-monitoring
          path: embassy-monitoring


  release:
    runs-on: ubuntu-22.04
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: embassy-monitoring
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: embacy-monitoring
          make_latest: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}