name: schedule.yml
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  get-empty-slots:
    runs-on: ubuntu-22.04
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run app
        run: go run embassy-monitoring
